### ISSUE TITLE
[BUG] BDFDB shows up as a virus

### ISSUE THREAD

**Issue by piotr25691** [Lightcord/Lightcord#142]
When you try to install plugins that require BDFDB, an error pops up claiming BDFDB is a virus and it won't let you to use it.

**To Reproduce**
1. Get any plugin that requires BDFDB (eg. http://betterdiscordlibrary.com/plugins/Old%20Title%20Bar).
2. Enable it.
3. Let it download BDFDB.
4. The error pops up.

**Expected behavior**
It shouldn't pop up this message and let me use it, because that makes many plugins unusable.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/71488561/102710007-94e9ea80-42af-11eb-9322-39f920c8dae3.png)

**Desktop**
 - OS: Windows 10
 - Version: 0.1.4 Quick Fix

**Comment by Basilou-R** [comment]
Same (fresh install)
![image](https://user-images.githubusercontent.com/17341929/102717112-7b14cb80-42e0-11eb-89f8-84c5e128bc95.png)
![image](https://user-images.githubusercontent.com/17341929/102717120-87008d80-42e0-11eb-87d4-28ed989a6e16.png)

**Comment by k6d** [comment]
disable plugin scan on BD settings or wait to whitelist

**Comment by JeanOUINA** [comment]
should work now anyway

**Comment by piotr25691** [comment]
Well, it doesn't. Still the same error.

**Comment by asorel1942** [comment]
> should work now anyway

Same as author, I'm still having the same issue with BDFDB and as a result am unable to utilize any plugins which depend on it.
