### ISSUE TITLE
Lightcord dosn't load [BUG]

### ISSUE THREAD

**Issue by VoidDave** [Lightcord/Lightcord#202]
Today i run my pc with win 10. I see that lightcord dosn't boot with discord (only normal discord loads)

I tried reinstaling it or reopening

**Comment by Lifell** [comment]
I have the same issue. I tried reinstalling. The client is just like when I install regular Discord. It's br00k.

**Comment by KajuKaVyapari** [comment]
same but on Arch Linux

**Comment by TheFourchette** [comment]
That's the same for me, I run Arch linux too

Even using the appimage it doesn't work

**Comment by B8nee** [comment]
Me too, when I open Lightdiscord doesn't start with the plugins, so it's like the normal discord boot

**Comment by Kyr4l** [comment]
same for me

**Comment by irockdude554** [comment]
Same for me.

**Comment by piotr25691** [comment]
and the same for me meaning my theme is no longer

**Comment by ArjixGamer** [comment]
same for me

**Comment by Voya42** [comment]
Same for me :/

**Comment by vsedov** [comment]
If im not mistaken it might actually be the new discord update more than lightcord it self , give it a few days it should be back up .

**Comment by TheFourchette** [comment]
> If im not mistaken it might actually be the new discord update more than lightcord it self , give it a few days it should be back up .

You may be right

**Comment by ArjixGamer** [comment]
But lightcord itself claims that a discord update cant break it...

**Comment by Lamborghini446** [comment]
same for me.

**Comment by vsedov** [comment]
@ArjixGamer where ? Id love to see where you got this info from.. Its a wrapper. Its not a different. Client.

**Comment by vsedov** [comment]
@ArjixGamer well i don't see any other updates made.  Im going to take the assumption its a large update , again people saying same and all of that.  Is just a bit annoying . Again wait a few days , ought tl go back to normal .

**Comment by JeanOUINA** [comment]
should be fixed by latest release. Feel free to reopen if it doesn't.

**Comment by Kyr4l** [comment]
still broken, it doesn't even load anymore, it just shows the console on start
![image](https://user-images.githubusercontent.com/24955106/110543134-356ede80-812a-11eb-8e2a-d2f74b02081d.png)

**Comment by ArjixGamer** [comment]
> I'd like to know, where did you get that info?
To whoever replied to me and deleted his message (quote above) so I only know what you asked for from my notification:
I got that info from the readme of the repo. So if the readme itself is saying it then I am allowed to believe it's trustworthy, right?
